### ISSUE TITLE
Interested in contributing GitHub wiki-related actions

### ISSUE THREAD

**Issue by jcbhmr** [wow-actions/.github#1]
<details><summary>outdated</summary>

Hello @bubkoo! 👋

I was wondering if this organization (@wow-actions) would consider creating a new wow-actions/publish-to-github-wiki or similar repo to publish in-source Markdown docs to GitHub wiki

**The reason why I ask:** I'm not a very good GitHub actions guy. @wow-actions is. Hence, it might be cool for you to bring an existing GitHub Action into the fold or make a new version that solves the goal of publishing in-source markdown to a GitHub wiki.

**Why this is better than relying on existing actions:** Giving the `wow-actions/*` organization scope to something is _almost_ like making it an "official" GitHub Action. In fact, the wow-actions/something (I forget which one) is used in the GitHub tutorial (the demo repo walkthrough)! That's how I stumbled across this awesome GitHub Actions collection! ❤️ Having a wow-actions/publish-to-github-wiki or similar (wow-actions/github-wiki, etc, doesn't matter) would legitimize it (I hope) with this @wow-actions' prestige as "the place for cool actions".

Here's a list of prior art that I found:
- https://github.com/marketplace/actions/wiki-sync
- https://github.com/marketplace/actions/wiki-action
- https://github.com/marketplace/actions/update-wiki
- https://github.com/marketplace/actions/wiki-update
- https://github.com/marketplace/actions/github-wiki-sync-action
- https://github.com/marketplace/actions/publish-to-github-wiki
- https://github.com/marketplace/actions/wiki-page-creator-action
- https://github.com/marketplace/actions/github-wiki-action
- https://github.com/marketplace/actions/github-docs-to-wiki
- https://github.com/marketplace/actions/publish-readmes-to-github-wiki
- https://github.com/marketplace/actions/external-repo-wiki-sync-action
- https://github.com/marketplace/actions/bi-directional-wiki-sync-action
- https://github.com/marketplace/actions/update-wiki-with-php-project-documentation
- https://github.com/marketplace/actions/pencil_pusher

I'm just posing this as a suggestion. Thanks for your time reading this! 👋

**Comment by jcbhmr** [comment]
I've mentioned this issue in https://github.com/Andrew-Chen-Wang/github-wiki-action/discussions/19

**Comment by jcbhmr** [comment]
I think that this isn't likely to happen. 🤷‍♂️ Closing.

**Comment by jcbhmr** [comment]
Hello again @bubkoo! 👋 I've revived my interest in this idea because, guess what, the GitHub wiki action that I have been trying to improve just isn't enough. I think there need to be _four separate actions_ to achieve "maximum goodness". Thus, I'm shopping around multiple GitHub Actions -related organizations to see if they're interested in adding my projects under their umbrella. This appears to be a single-contributor @wow-actions organization, so sorry if I'm in the wrong spot here.

I am interested in adding GitHub Actions that would make it easy to sync a GitHub in-source folder like `/wiki/*.md` to the actual "wiki" tab on GitHub. This is useful for users who want to possibly:
- Autogenerate documentation but don't want to put it on GitHub Pages, so they put it on a wiki instead
- Allowing the normal GitHub flow of PRs + merges for wiki changes
- Letting users auto-generate other things like build data and post it to the wiki
- etc.

Particularily, there are 4 "things" that I see being useful to have actions for so that you can do something like this:

```yml
on:
  push:
    branches: "main"
    paths: wiki/**
jobs:
  source-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/source-to-wiki-links@v1
      - uses: wow-actions/upload-wiki@v1
```
```yml
on:
  gollum: null
  schedule:
    - cron: "0 0 * * *"
jobs:
  wiki-to-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/download-wiki@v1
      - uses: wow-actions/wiki-to-source-links@v1
      - uses: EndBug/add-and-commit@v9
```

- source-to-wiki-links: Rewrites links like `./Hello.md` to be `./Hello` since GitHub wikis don't do file extensions; also renames README.md to Home.md
- (publish|push|upload)-wiki: Pushes current folder or subfolder to the GitHub wiki
- (download|clone|pull)-wiki: Pulls the GitHub wiki to the current folder or sub folder
- wiki-to-source-links: Rewrites links like `./Hello` to `./Hello.(md|markdown|mdown,etc)` to work in source control; also renames Home.md to README.md
